Webshop2/Webshop2/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webshop2.Models;
using Webshop2.DatabaseControllers;
using MySql.Data.MySqlClient;


namespace Webshop2.Controllers
{
    public class StoreController : Controller
    {

        static ProductDBController ProdDataBase = new ProductDBController();
        static CategorieDBController CatDataBase = new CategorieDBController();
        public string categorieParameter;

        // GET: Store
        public ActionResult Index()
        {
            ViewBag.H1 = "Winkel";
            DatabaseControllers.ProductDBController prodControl = new DatabaseControllers.ProductDBController();
            //ViewBag.prijs = besteldbcontrol.HaalBestellingTotaalPrijsOp();
            List<Models.Product> producten = prodControl.haalProductGegevensOp();
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();
            ViewBag.merkFilters = prodControl.getMerken();
            ViewBag.maatFilters = prodControl.getMaten();
            ViewBag.geslachtFilters = prodControl.getGeslacht();
            return View(producten);
        }

        public ActionResult ProductDetail(int productID)
        {
            ViewBag.H1 = "Product Detail";
            DatabaseControllers.ProductDBController prodControl = new DatabaseControllers.ProductDBController();
            //ViewBag.prijs = besteldbcontrol.HaalBestellingTotaalPrijsOp();
            List<Product> producten = prodControl.haalProductDetailGegevensOp(productID);
            ViewBag.H1 = "Product Detail";
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();
            ProductDBController prodDBControl = new ProductDBController();
            ViewBag.merkFilters = prodDBControl.getMerken();
            ViewBag.maatFilters = prodDBControl.getMaten();
            ViewBag.geslachtFilters = prodDBControl.getGeslacht();

            foreach (Product produ in producten)
            {
                ViewBag.productID = produ.productID;
                ViewBag.productNaam = produ.productNaam;
                ViewBag.productPrijs = produ.productPrijs;
                ViewBag.productMerk = produ.productMerk;
                ViewBag.productDetail = produ.productDetail;
                ViewBag.productAfbeelding = produ.productAfbeelding;
            }
            return View(producten);
        }

        public ActionResult ProductToevoegen()
        {
            
                ViewBag.H1 = "Toevoegen producten";
                DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
                ViewBag.categorieen = catControl.haalCatNamenOp();

                ProductDBController prodDBControl = new ProductDBController();
                ViewBag.merkFilters = prodDBControl.getMerken();
                ViewBag.maatFilters = prodDBControl.getMaten();
                ViewBag.geslachtFilters = prodDBControl.getGeslacht();
                ViewBag.productLijstje = prodDBControl.haalProductGegevensOp();
            if (Session["AdminLoggedIn"] != null)
            {
                return View();
            }
            else
            {
                ViewBag.H1 = "Niet ingelogd";
                return View("LoginFout");
            }
        }
        public ActionResult ProductToegevoegd(Product product, HttpPostedFileBase file, int categorieID, string productGeslacht)
        {
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();
            ProductDBController prodDBControl = new ProductDBController();
            ViewBag.merkFilters = prodDBControl.getMerken();
            ViewBag.maatFilters = prodDBControl.getMaten();
            ViewBag.geslachtFilters = prodDBControl.getGeslacht();
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("/productImages"), pic);
                    // file is uploaded
                    product.ImageData = pic;
                    file.SaveAs(path);

                }
                ViewBag.H1 = "Product geregistreerd.";
                product.productCat = categorieID;
                product.productGeslacht = productGeslacht;
                ProdDataBase.RegisterProduct(product);
                ProdDataBase.registerUitvoering(product.productMaat, product.productKleur, product.uitvoeringVoorraad);
                return View();
            }
            else
            {
                return View("ProductToevoegen", product);
            }
            //afhendelen van de foto upload

        }
        public ActionResult ProductWijzigen()
        {
            
                ViewBag.H1 = "Wijzigen producten";
                DatabaseControllers.ProductDBController prodControl = new DatabaseControllers.ProductDBController();
                //ViewBag.prijs = besteldbcontrol.HaalBestellingTotaalPrijsOp();
                List<Models.Product> producten = prodControl.haalProductGegevensOp();
                DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
                ViewBag.categorieen = catControl.haalCatNamenOp();
                ViewBag.merkFilters = prodControl.getMerken();
                ViewBag.maatFilters = prodControl.getMaten();
                ViewBag.geslachtFilters = prodControl.getGeslacht();
                ViewBag.productLijstje = prodControl.haalProductGegevensOp();
            if (Session["AdminLoggedIn"] != null)
            {
                return View();
            }
            else
            {
                ViewBag.H1 = "Niet ingelogd";
                return View("LoginFout");
            }

        }
        public ActionResult wijzigenProduct(Product product, int prodID)
        {
            
                ViewBag.H1 = "Toevoegen producten";
                DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
                ViewBag.categorieen = catControl.haalCatNamenOp();
                ProductDBController prodDBControl = new ProductDBController();
                List<Product> producten = prodDBControl.haalProductDetailGegevensOp(prodID);
                ViewBag.merkFilters = prodDBControl.getMerken();
                ViewBag.maatFilters = prodDBControl.getMaten();
                ViewBag.geslachtFilters = prodDBControl.getGeslacht();
                ViewBag.productLijstje = prodDBControl.haalProductGegevensOp();
                foreach (Product produ in producten)
                {
                    ViewBag.productID = produ.productID;
                    ViewBag.productNaam = produ.productNaam;
                    ViewBag.productPrijs = produ.productPrijs;
                    ViewBag.productMerk = produ.productMerk;
                    ViewBag.productDetail = produ.productDetail;
                }
            if (Session["AdminLoggedIn"] != null)
            {
                prodDBControl.UitvoeringWijzigen(product, prodID);
                return View();
            }
            else
            {
                ViewBag.H1 = "Niet ingelogd";
                return View("LoginFout");
            }
        }
        public ActionResult ProductGeWijzigd(Product product, int id)
        {
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();
            ProductDBController prodDBControl = new ProductDBController();
            ViewBag.merkFilters = prodDBControl.getMerken();
            ViewBag.maatFilters = prodDBControl.getMaten();
            ViewBag.geslachtFilters = prodDBControl.getGeslacht();
            ViewBag.H1 = "Product is gewijzigd";
            if (ModelState.IsValid)
            {
                prodDBControl.WijzigenProduct(product, id);
                return View();
            }
            else
            {
                return View("ProductWijzigen", product);
            }
        }
        public ActionResult UitvoeringWijzigen(int prodID)
        {

            ViewBag.H1 = "Wijzigen uitvoeringen";
            DatabaseControllers.ProductDBController prodControl = new DatabaseControllers.ProductDBController();
            //ViewBag.prijs = besteldbcontrol.HaalBestellingTotaalPrijsOp();
            List<Models.Product> producten = prodControl.haalProductDetailGegevensOp(prodID);
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();
            ViewBag.merkFilters = prodControl.getMerken();
            ViewBag.maatFilters = prodControl.getMaten();
            ViewBag.geslachtFilters = prodControl.getGeslacht();
            ViewBag.productLijstje = prodControl.haalProductDetailGegevensOp(prodID);
            if (Session["AdminLoggedIn"] != null)
            {
                return View();
            }
            else
            {
                ViewBag.H1 = "Niet ingelogd";
                return View("LoginFout");
            }

        }
        public ActionResult WijzigenUitvoering(int uitID)
        {

            ViewBag.H1 = "Uitvoering wijzigen";
            DatabaseControllers.CategorieDBController catControl = new DatabaseControllers.CategorieDBController();
            ViewBag.categorieen = catControl.haalCatNamenOp();

Webshop2/Webshop2/Views/Store/CategorieToevoegen.cshtml
@using Webshop2.Models
@model Categorie

@{
    ViewBag.Title = "Index";
}

<h1>@ViewBag.H1</h1>

    <form name="productToevoegen" method="post" action="/Store/CategorieToegvoegd">

    <table>
        <tr>
            <td>
                <label>Categorie Naam :</label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.categorieNaam)
            </td>
            <td id="validationerror">
                @Html.ValidationMessageFor(model => model.categorieNaam)
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Toevoegen">
            </td>
        </tr>
    </table>

</form>

Webshop2/Webshop2/Views/Store/Index.cshtml
@using Webshop2.Models
@model List<Product>

@{
    ViewBag.Title = "Index";
}

<h1>@ViewBag.H1</h1>

@{foreach (Product prod in Model)
{
    string afbeelding = prod.productID + ".png";
    <div class="naastElkaar">

        <a href="/Store/ProductDetail?productID=@prod.productID" id="linknaastelkaar"><img src="~/ProductImages/@prod.productAfbeelding" alt="afbeelding" height="00" width="200" /></a>
        <div id="textnaastelkaar">
            <b>Naam: </b>@prod.productNaam
            <br />
            <b>Prijs: </b>€ @prod.productPrijs
            <br />
        </div>

    </div>

}}

Webshop2/Webshop2/Views/Store/ProductGeWijzigd.cshtml
@{
    ViewBag.Title = "ProductGeWijzigd";
}

<h1>@ViewBag.H1</h1>


<p>Het product is met succes gewijzigd!</p>
<p><a href="/Store/ProductWijzigen">Klik hier om nog een product te wijzigen.</a></p>

Webshop2/Webshop2/Views/Store/ProductToegevoegd.cshtml
@{
    ViewBag.Title = "Product Toegevoegd";
}

<h1>@ViewBag.H1</h1>

<div>
    <p>U heeft het product toegevoegd aan het assortiment!</p>

</div>

Webshop2/Webshop2/Views/Store/ProductToevoegen.cshtml
@using Webshop2.Models
@model Product


@{
    ViewBag.Title = "create";
}

<h1>@ViewBag.H1</h1>


<div id='createform'>

    <form name="productToevoegen" method="post" action="/Store/ProductToegevoegd" enctype="multipart/form-data">

        <table>
            <tr>
                <td>
                    <label>Naam:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productNaam)
                </td>
                <td id="validationerror">
                    @Html.ValidationMessageFor(model => model.productNaam)
                </td>
            </tr>
            <tr>
                <td>
                    <label>Merk:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productMerk)
                    @Html.ValidationMessageFor(model => model.productMerk)
                </td>
            </tr>
            <tr>
                <td>
                    <label>Categorie:</label>
                </td>
                <td>

                    <select name="categorieID">
                        @foreach (Categorie cat in @ViewBag.categorieen)
                        {
                            <option value="@cat.categorieID">@cat.categorieNaam </option>

                        }
                    </select>


                </td>
                <td id="validationerror">
                    @Html.ValidationMessageFor(model => model.categorieNaam)
                </td>
            </tr>
            <tr>
                <td>
                    <label>Geslacht:</label>
                </td>
                <td>
                    <select name="productGeslacht">
                        <option value="M">Man</option>
                        <option value="V">Vrouw</option>
                        <option value="O">Overig</option>
                    </select>
                </td>


            </tr>
            <tr>

                <td>
                    <label>Prijs:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productPrijs)
                </td>
                <td id="validationerror">
                    @Html.ValidationMessageFor(model => model.productPrijs)
                </td>
            </tr>
            <tr>

                <td>
                    <label>Details:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productDetail)
                </td>
                <td id="validationerror">
                    @Html.ValidationMessageFor(model => model.productDetail)
                </td>
            </tr>
            <tr>
                <td>
                    <label for="file">Upload Afbeelding:</label>
                </td>
                <td>
                    @using (Html.BeginForm("ProductToegevoegd", "Store", FormMethod.Post,
                                new { enctype = "multipart/form-data" }))
                    {
                        @*<label for="file">Upload Image:</label>*@
                        <input type="file" name="file" id="file" style="width: 100%;" />
                        @*<input type="submit" value="Upload" class="submit" />*@
                    }

                </td>
            </tr>
            <tr>
                <td>
                    <label>Voorraad:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.uitvoeringVoorraad)
                </td>
            </tr>
            <tr>
                <td>
                    <label>Maat:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productMaat)
                </td>
            </tr>
            <tr>
                <td>
                    <label>Kleur:</label>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.productKleur)
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Toevoegen">
                </td>
            </tr>
        </table>

    </form>
</div>

Webshop2/Webshop2/Views/Store/ProductVerwijderd.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>@ViewBag.H1</h1>

<p>Het product is met succes verwijderd!</p>
<p><a href="/Store/ProductVerwijderen">Klik hier om nog een product te verwijderen.</a></p>

Webshop2/Webshop2/Views/Store/ProductVerwijderen.cshtml
@using Webshop2.Models
@model List<Product>

@{
    ViewBag.Title = "Index";
}

<h1>@ViewBag.H1</h1>

<form name="ProdutVerwijderen" method="post" action="/Store/ProductVerwijderd">

    <table>
        <tr>
            <td>
                <label>Product:</label>
            </td>
            <td>

                <select name="productID">
                    @{foreach (Product prod in Model)
                    {
                        <option value="@prod.productID">@prod.productNaam </option>
                    }
                    }
                </select>


            </td>

        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Verwijderen">
            </td>
        </tr>
    </table>

</form>

Webshop2/Webshop2/Views/Store/ProductWijzigen.cshtml
@using Webshop2.Models
@model List<Product>

@{
    ViewBag.Title = "ProductWijzigen";
}

<h1>@ViewBag.H1</h1>


    <table>
        <tr class="h4">
            <td>Naam</td>
            <td>Merk</td>
            <td>Prijs</td>
            <td></td>
        </tr>

        @{
    foreach (Product prod in ViewBag.productLijstje)
    {
        <tr>
            <td>@prod.productNaam</td>
            <td>@prod.productMerk</td>
            <td>@prod.productPrijs</td>
            <td><a href="/Store/wijzigenProduct?prodID=@prod.productID">Wijzigen</a></td>
        </tr>
    }
        }

    </table>

Webshop2/Webshop2/Views/Store/ReactieBeheer.cshtml
@{
    ViewBag.Title = "ReactieBeheer";
}

<h2>ReactieBeheer</h2>
<p>Klik op het prullenbak icoon om een (ongewenste) reactie te verwijderen. <br><b>Let op!</b> Eenmaal verwijderd kunnen de reacties niet teruggehaald worden. </p>
<form action="/Store/ReactieVerwijderen" method="post">
    <table id="adminview">
        <tr>
            <td style="width: 40px"><b>ID</b></td>
            <td style="width: 100px"><b>Gebruiker</b></td>
            <td style="width: 500px"><b>Beoordeling</b></td>
            <td style="width: 20px"><b>Rating</b></td>
            <td style="width: 40px"></td>
        </tr>
        @Html.Raw(ViewBag.reacties)
    </table>
</form>

Webshop2/Webshop2/Views/Store/UitvoeringWijzigen.cshtml
@using Webshop2.Models
@model List<Product>

@{
    ViewBag.Title = "ProductWijzigen";
}

<h1>@ViewBag.H1</h1>


<table>
    <tr class="h4">
        <td>Maat</td>
        <td>Kleur</td>
        <td>Voorraad</td>
        <td></td>
    </tr>

    @{
        foreach (Product prod in ViewBag.productLijstje)
        {
            <tr>
                <td>@prod.productMaat</td>
                <td>@prod.productKleur</td>
                <td>@prod.uitvoeringVoorraad</td>
                <td><a href="/Store/WijzigenUitvoering?uitID=@prod.productUitvoeringID">Wijzigen</a></td>
            </tr>
        }
    }

</table>

Webshop2/Webshop2/Views/Store/WijzigenUitvoering.cshtml
@using Webshop2.Models;
@model Product
@{
    ViewBag.Title = "UitvoeringWijzigen";
}

<h1>@ViewBag.H1</h1>

<form name="UitvoeringWijzigen" method="post" action="/Store/UitvoeringGeWijzigd">
    <table>
        <tr>
            <td>
                <input type="hidden" name="uitvoeringID" value="@ViewBag.productUitvoeringID" class="field left" readonly>
            </td>
        </tr>
        <tr>
            <td>
                <label>Kleur : <br /><b>@ViewBag.productKleur</b> </label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.productKleur)
            </td>
            <td id="validationerror">
                @Html.ValidationMessageFor(model => model.productKleur)
            </td>
        </tr>
        <tr>
            <td>
                <label>Maat : <br /> <b>@ViewBag.productMaat</b> </label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.productMaat)
                @Html.ValidationMessageFor(model => model.productMaat)
            </td>
        </tr>
        <td>
            <label>Voorraad : <br /> <b>@ViewBag.uitvoeringVoorraad</b> </label>
        </td>
        <td>
            @Html.TextBoxFor(model => model.uitvoeringVoorraad)
        </td>
        <td id="validationerror">
            @Html.ValidationMessageFor(model => model.uitvoeringVoorraad)
        </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Wijzigen">
            </td>
        </tr>
    </table>
</form>

Webshop2/Webshop2/Views/Store/filterProducten.cshtml
@using Webshop2.Models
@model List<Product>
@{
    ViewBag.Title = "Gevonden Producten";
}

<h1>@ViewBag.H1</h1>

@{foreach (Product prod in Model)
{
    string afbeelding = prod.productID + ".png";
    <div class="naastElkaar">

        <a href="/Store/ProductDetail?productID=@prod.productID" id="linknaastelkaar"><img src="~/ProductImages/@prod.productAfbeelding" alt="afbeelding" height="00" width="200" /></a>
        <div id="textnaastelkaar">
            <b>Naam: </b>@prod.productNaam
            <br />
            <b>Prijs: </b>€ @prod.productPrijs
            <br />
        </div>

    </div>
}}

Webshop2/Webshop2/Views/Store/wijzigenProduct.cshtml
@using Webshop2.Models;
@model Product
@{
    ViewBag.Title = "ProductWijzigen";
}

<h1>@ViewBag.H1</h1>

<form name="productWijzigen" method="post" action="/Store/ProductGeWijzigd">
    <table>
        <tr>
            <td>
                Product id :
            </td>
            <td>
                <input type="text" name="ID" value="@ViewBag.productID" class="field left" readonly>
            </td>
        </tr>
        <tr>
            <td>
                <label>Product Naam : <br /><b>@ViewBag.productNaam</b> </label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.productNaam)
            </td>
            <td id="validationerror">
                @Html.ValidationMessageFor(model => model.productNaam)
            </td>
        </tr>
        <tr>
            <td>
                <label>Product merk : <br /> <b>@ViewBag.productMerk</b> </label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.productMerk)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.productMerk)
            </td>
        </tr>
        <td>
            <label>Product Prijs : <br /> <b>€@ViewBag.productPrijs</b> </label>
        </td>
        <td>
            @Html.TextBoxFor(model => model.productPrijs)
        </td>
        <td id="validationerror">
            @Html.ValidationMessageFor(model => model.productPrijs)
        </td>
        </tr>
        <tr>

            <td>
                <label>
                    Product Details : <br /><b>
                        @ViewBag.productDetail
                    </b>
                </label>
            </td>
            <td>
                @Html.TextBoxFor(model => model.productDetail)
            </td>
            <td id="validationerror">
                @Html.ValidationMessageFor(model => model.productDetail)
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <a href="/Store/UitvoeringWijzigen?prodID=@ViewBag.productID">Wijzig Uitvoeringen</a>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Wijzigen">
            </td>
        </tr>
    </table>
</form>

Webshop2/Webshop2/Views/Store/zoekProducten.cshtml
@using Webshop2.Models
@model List<Product>

@{
    ViewBag.Title = "Index";
}

<h1>@ViewBag.H1</h1>

@{foreach (Product prod in Model)
{
    string afbeelding = prod.productID + ".png";
    <div class="naastElkaar">

        <a href="/Store/ProductDetail?productID=@prod.productID" id="linknaastelkaar"><img src="~/ProductImages/@prod.productAfbeelding" alt="afbeelding" height="00" width="200" /></a>
        <div id="textnaastelkaar">
            <b>Naam: </b>@prod.productNaam
            <br />
            <b>Prijs: </b>€ @prod.productPrijs
            <br />
        </div>

    </div>
}}